const CONSTANTS = {
    SLIDE: document.querySelector(".slide"),
    SLIDE_CONTAINER: document.querySelector(".slide-container"),
    SLIDE_ASPECT_RATIO_STR: "4 / 3",
    SLIDE_ASPECT_RATIO: null,
    SLIDE_WIDTH: null,
    SLIDE_HEIGHT: null,
    MAIN_CONTENT_AREA: document.querySelector(".main-content-area"),
    SIDEBAR: document.querySelector(".sidebar"),
    ADD_SLIDE_BTN: document.querySelector(".add-slide-btn"),
    ADD_SLIDE_ELEMENT_BTN: document.querySelector(".add-slide-element-btn"),
    MIN_ELEMENT_SIZE: 30,
    INCREASE_FONT_SIZE_BTN: document.querySelector(".increase-font-size-btn"),
    DECREASE_FONT_SIZE_BTN: document.querySelector(".decrease-font-size-btn"),
    SET_TEXTLAYOUT_LEFT_BTN: document.querySelector(".set-textlayout-left-btn"),
    SET_TEXTLAYOUT_CENTER_BTN: document.querySelector(".set-textlayout-center-btn"),
    SET_TEXTLAYOUT_RIGHT_BTN: document.querySelector(".set-textlayout-right-btn"),
    BACKGROUND_COLOR_INPUT: document.querySelector(".background-color-input"),
    BACKGROUND_TRANSPAENCY_INPUT: document.querySelector(".background-transparency-input"),
    BORDER_COLOR_INPUT: document.querySelector(".border-color-input"),
    INCREASE_BORDER_WIDTH_BTN: document.querySelector(".increase-border-width-btn"),
    DECREASE_BORDER_WIDTH_BTN: document.querySelector(".decrease-border-width-btn"),
    INCREASE_BORDER_RADIUS_BTN: document.querySelector(".increase-border-radius-btn"),
    DECREASE_BORDER_RADIUS_BTN: document.querySelector(".decrease-border-radius-btn"),
    TEXT_COLOR_INPUT: document.querySelector(".text-color-input"),
    DELETE_SLIDE_ELEMENT_BTN: document.querySelector(".delete-slide-element-btn"),
    PRESENT_BNT: document.querySelector(".present-btn"),
    PRESENT_OVERLAY: document.querySelector(".present-overlay"),
    PRESENT_OVER_OVERLAY: document.querySelector(".present-over-overlay"),
    SLIDE_ELEMENT_CONTEXTMENU: document.querySelector(".slide-element-contextmenu"),
    BRING_SLIDE_ELEMENT_TO_FRONT_BTN: document.querySelector(".bring-slide-element-to-front-btn"),
    BRING_SLIDE_ELEMENT_TO_BACK_BTN: document.querySelector(".bring-slide-element-to-back-btn"),
    FONT_FAMILY_SELECT: document.querySelector(".font-family-select"),
    FONT_STYLE_SELECT: document.querySelector(".font-style-select"),
    PRESENTATION_NAME_OUTPUT: document.querySelector("#presentation_name_output"),
    SAVED_SECONDS_AGO_OUTPUT: document.querySelector("#saved_seconds_ago_output"),
    DUPLICATE_SLIDE_ELEMENT_BTN: document.querySelector(".duplicate-slide-element-btn"),
}

CONSTANTS.SLIDE_ASPECT_RATIO = eval(CONSTANTS.SLIDE_ASPECT_RATIO_STR)
CONSTANTS.SLIDE_WIDTH = 1000 * CONSTANTS.SLIDE_ASPECT_RATIO
CONSTANTS.SLIDE_HEIGHT = 1000 / CONSTANTS.SLIDE_ASPECT_RATIO
